version: 0.2
phases:
    install:
        commands:
            - 'sudo npm install'
    build:
        commands:
            - 'npm run build-ts'
artifacts:
    type: zip
    files:
        - package.json
        - package-lock.json
        - 'dist/**/*'